### ISSUE TITLE
idea

### ISSUE THREAD

**Issue by Crypt97** [HimmelKreis4865/BetterNick#4]
only color change? realname no change

**Comment by HimmelKreis4865** [comment]
Which color change do you mean? 

So for /nick realname do not use the real name of a player, use the nickname of him. Then you should get a message of this kind: "Test is HimmelKreis4865" as an example.
To change your nickname so the following:
/nick set test
And now you can see the realname of him:
/nick realname test
Now you get the message:
"test is _Your Name_"

**Comment by Crypt97** [comment]
Your real name cannot be changed with just the colors

**Comment by HimmelKreis4865** [comment]
So, I Think that's impossible. I never used a message like "Only Colors!" or "Successful changes real name colors". 
Try to use latest build.
with _/nick set §fCrypt_ you can change ypur name and not only color!
Maybe you are using an other plugin that has a command called nick?

**Comment by Wertzui123** [comment]
If I understand this right: You cannot change your name.

**Comment by HimmelKreis4865** [comment]
Crypt97, tell me please exactly your problem, otherwise I'll close this issue in a few days!

**Comment by HimmelKreis4865** [comment]
So, you're too late. This Issue is now closed
